// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var Value$ReasonPowerplug = require("./Value.bs.js");

var Value = Value$ReasonPowerplug.Make({});

function Active(Props) {
  var onChange = Props.onChange;
  var children = Props.children;
  var tmp = {
    initial: false,
    children: (function (param) {
        var set = param.set;
        return Curry._1(children, {
                    active: param.value,
                    onMouseDown: (function (param) {
                        return Curry._1(set, (function (param) {
                                      return true;
                                    }));
                      }),
                    onMouseUp: (function (param) {
                        return Curry._1(set, (function (param) {
                                      return false;
                                    }));
                      })
                  });
      })
  };
  if (onChange !== undefined) {
    tmp.onChange = Caml_option.valFromOption(onChange);
  }
  return React.createElement(Value.make, tmp);
}

var make = Active;

exports.Value = Value;
exports.make = make;
/* Value Not a pure module */
