// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var Value$ReasonPowerplug = require("./Value.bs.js");

var Value = Value$ReasonPowerplug.Make({});

function Counter(Props) {
  var initial = Props.initial;
  var onChange = Props.onChange;
  var children = Props.children;
  var tmp = {
    initial: initial,
    children: (function (param) {
        var set = param.set;
        return Curry._1(children, {
                    count: param.value,
                    set: set,
                    inc: (function (param) {
                        return Curry._1(set, (function (value) {
                                      return value + 1 | 0;
                                    }));
                      }),
                    dec: (function (param) {
                        return Curry._1(set, (function (value) {
                                      return value - 1 | 0;
                                    }));
                      }),
                    incBy: (function (number) {
                        return Curry._1(set, (function (value) {
                                      return value + number | 0;
                                    }));
                      }),
                    decBy: (function (number) {
                        return Curry._1(set, (function (value) {
                                      return value - number | 0;
                                    }));
                      }),
                    reset: param.reset
                  });
      })
  };
  if (onChange !== undefined) {
    tmp.onChange = Caml_option.valFromOption(onChange);
  }
  return React.createElement(Value.make, tmp);
}

var make = Counter;

exports.Value = Value;
exports.make = make;
/* Value Not a pure module */
