// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var Value$ReasonPowerplug = require("./Value.bs.js");

var Value = Value$ReasonPowerplug.Make({});

function FocusManager(Props) {
  var onChange = Props.onChange;
  var children = Props.children;
  var canBlur = {
    contents: true
  };
  var tmp = {
    initial: false,
    children: (function (param) {
        var set = param.set;
        var value = param.value;
        return Curry._1(children, {
                    focused: value,
                    blur: (function (param) {
                        if (value === true) {
                          return (document.activeElement.blur());
                        }
                        
                      }),
                    tabIndex: -1,
                    onBlur: (function (param) {
                        if (canBlur.contents) {
                          return Curry._1(set, (function (param) {
                                        return false;
                                      }));
                        }
                        
                      }),
                    onFocus: (function (param) {
                        return Curry._1(set, (function (param) {
                                      return true;
                                    }));
                      }),
                    onMouseDown: (function (param) {
                        canBlur.contents = false;
                        
                      }),
                    onMouseUp: (function (param) {
                        canBlur.contents = true;
                        
                      })
                  });
      })
  };
  if (onChange !== undefined) {
    tmp.onChange = Caml_option.valFromOption(onChange);
  }
  return React.createElement(Value.make, tmp);
}

var make = FocusManager;

exports.Value = Value;
exports.make = make;
/* Value Not a pure module */
