// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var Value$ReasonPowerplug = require("./Value.bs.js");

var Value = Value$ReasonPowerplug.Make({});

function Input(Props) {
  var initialOpt = Props.initial;
  var onChange = Props.onChange;
  var children = Props.children;
  var initial = initialOpt !== undefined ? initialOpt : "";
  var tmp = {
    initial: initial,
    children: (function (param) {
        var set = param.set;
        return Curry._1(children, {
                    value: param.value,
                    reset: param.reset,
                    set: set,
                    onChange: (function (e) {
                        var newValue = e.target.value;
                        return Curry._1(set, (function (param) {
                                      return newValue;
                                    }));
                      })
                  });
      })
  };
  if (onChange !== undefined) {
    tmp.onChange = Caml_option.valFromOption(onChange);
  }
  return React.createElement(Value.make, tmp);
}

var make = Input;

exports.Value = Value;
exports.make = make;
/* Value Not a pure module */
