// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var Value$ReasonPowerplug = require("./Value.bs.js");

var Value = Value$ReasonPowerplug.Make({});

function Toggle(Props) {
  var initialOpt = Props.initial;
  var onChange = Props.onChange;
  var children = Props.children;
  var initial = initialOpt !== undefined ? initialOpt : false;
  var tmp = {
    initial: initial,
    children: (function (param) {
        var set = param.set;
        return Curry._1(children, {
                    on: param.value,
                    toggle: (function (param) {
                        return Curry._1(set, (function (value) {
                                      return !value;
                                    }));
                      }),
                    set: set,
                    reset: param.reset
                  });
      })
  };
  if (onChange !== undefined) {
    tmp.onChange = Caml_option.valFromOption(onChange);
  }
  return React.createElement(Value.make, tmp);
}

var make = Toggle;

exports.Value = Value;
exports.make = make;
/* Value Not a pure module */
