// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");

function Make(M) {
  var Value$Make = function (Props) {
    var initial = Props.initial;
    var onChangeOpt = Props.onChange;
    var children = Props.children;
    var onChange = onChangeOpt !== undefined ? onChangeOpt : (function (_value) {
          
        });
    var match = React.useReducer((function (state, action) {
            return Curry._1(action._0, state);
          }), initial);
    var dispatch = match[1];
    return Curry._1(children, {
                value: match[0],
                set: (function (updater) {
                    return Curry._1(dispatch, /* Set */{
                                _0: updater
                              });
                  }),
                reset: (function (param) {
                    return Curry._1(onChange, initial);
                  })
              });
  };
  return {
          make: Value$Make
        };
}

exports.Make = Make;
/* react Not a pure module */
